name: Progress
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: sudo apt-get install --no-install-recommends libfontconfig-dev
          - uses: actions/checkout@v4
            with:
                fetch-depth: 0
          - run: rustup update
          - run: cargo run --package progress-tracker --release -- . _site
          - uses: actions/upload-pages-artifact@v3
          - uses: stefanzweifel/git-auto-commit-action@v5
            with:
              file_pattern: problems
              commit_message: Update problems [skip ci]
    deploy:
        needs: build
        permissions:
            id-token: write
            pages: write
        runs-on: ubuntu-latest
        steps:
          - uses: actions/deploy-pages@v4
